language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

env:
  global:
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: nightly

before_install:
  - composer self-update

install:
  - composer install
  - ./vendor/bin/simple-phpunit install

script:
  - ./vendor/bin/simple-phpunit --coverage-clover=coverage.xml
  - ./vendor/bin/php-cs-fixer fix --diff --dry-run -v'
  - ./bin/console lint:yaml config
  - ./bin/console lint:twig templates
  #- ./bin/console lint:xliff translations
  #- ./bin/console security:check --end-point=http://security.sensiolabs.org/check_lock
  - composer validate --strict
  - ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction

after_success:
  - travis_retry bash <(curl -s https://codecov.io/bash)
