services:
    _defaults:
        public: true

    test.App\Consumer\CallEventConsumer:
        alias: App\Consumer\CallEventConsumer
        public: true

    test.App\Mailer\NewContactMailer:
        alias: App\Mailer\NewContactMailer
        public: true
